// <auto-generated />
namespace OneToManyMapping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_NameCost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_NameCost));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201007201_Added_NameCost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
