// <auto-generated />
namespace ShoppingCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updated10thMar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updated10thMar));
        
        string IMigrationMetadata.Id
        {
            get { return "201803100908528_Updated10thMar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
