USE TECHLABS
GO

CREATE TABLE BOOKMARKUSERS
(
ID INT,
NAME VARCHAR(30),
EMAIL VARCHAR(30),
PASSWORD VARCHAR(20),
);

ALTER TABLE BOOKMARKUSERS DROP CONSTRAINT PK_USERS

ALTER TABLE DBO.BOOKMARKUSERS ADD CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED(ID)



EXEC SP_COLUMNS BOOKMARKUSERS;
EXEC SP_COLUMNS BOOKMARKS;

ALTER TABLE BOOKMARKUSERS DROP COLUMN ID 
ALTER TABLE BOOKMARKUSERS ADD ID INT IDENTITY(1,1)

INSERT INTO BOOKMARKUSERS VALUES('Brijesh','brijeshyadav152@gmail.com','@PASSWORD')

DELETE FROM BOOKMARKUSERS WHERE ID = 2

CREATE TABLE BOOKMARKS
(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
USERID INT FOREIGN KEY REFERENCES BOOKMARKUSERS(ID),
DATE DATETIME,
URL VARCHAR(255),
);


ALTER TABLE BOOKMARKS ALTER COLUMN DATE DATE NOT NULL

SELECT * FROM BOOKMARKUSERS;
SELECT * FROM BOOKMARKS;

DELETE FROM BOOKMARKUSERS WHERE ID = 1

TRUNCATE TABLE BOOKMARKUSERS;
TRUNCATE TABLE BOOKMARKS;

INSERT INTO BOOKMARKS VALUES(1, 'ADANAME',22, GETDATE(),'@URL')

ALTER TABLE BOOKMARKS
ADD CONSTRAINT FK_BOOKMARK_USERS FOREIGN KEY (USERID)     
    REFERENCES DBO.BOOKMARKUSERS (ID);

Alter Table BOOKMARKUSERS
ADD UNIQUE (email);


ALTER TABLE BOOKMARKS DROP CONSTRAINT PK__Bookmark__3213E83F18A777DB

ALTER TABLE BOOKMARKS DROP COLUMN ID 
ALTER TABLE BOOKMARKS ADD ID INT IDENTITY(1,1)