Use Techlabs

DROP TABLE EMP_CONSTRAINT;

CREATE TABLE EMP_CONSTRAINT (
 EMPNO               integer NOT NULL,
 ENAME               varchar(10),
 JOB                 varchar(9),
 EMAIL				 varchar(30) UNIQUE,
 SAL                 money,
 DEPTNO              integer NOT NULL,
 CONSTRAINT EPRIMARY_KEY PRIMARY KEY (EMPNO),
 CONSTRAINT ESALARY_CHECK CHECK ( SAL >= 800 AND SAL <= 2200)
 );


 INSERT INTO EMP_CONSTRAINT VALUES (7839,'KING','PRESIDENT',NULL,1500,10); --Successfully Inserted
 INSERT INTO EMP_CONSTRAINT VALUES (7849,'KING','PRESIDENT','KING@EMP.COM',5000,10); -- Will fail Salary Check Constraint
 INSERT INTO EMP_CONSTRAINT VALUES (7821,'KING','PRESIDENT','KING@EMP.COM',2000,10); --Will fail Primary Key Check Constraint
 INSERT INTO EMP_CONSTRAINT VALUES (7821,'KING','PRESIDENT','KING@EMP.COM',2000,10); --Successfully Inserted 
 INSERT INTO EMP_CONSTRAINT VALUES (7820,'KING','PRESIDENT','KING@EMP.COM',2000,10); --WILL FAIL UNIQUE KEY Constraint

 Select * FROM EMP_CONSTRAINT;