USE TECHLABS;

DROP TABLE EMP;
DROP TABLE DEPT;

CREATE TABLE DEPT (
 DEPTNO              INTEGER NOT NULL,
 DNAME               VARCHAR(14),
 LOC                 VARCHAR(13),
 CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP (
 EMPNO               INTEGER NOT NULL,
 ENAME               VARCHAR(10),
 JOB                 VARCHAR(9),
 MGR                 INTEGER CONSTRAINT EMP_SELF_KEY REFERENCES EMP (EMPNO),
 HIREDATE            DATETIME,
 SAL                 MONEY,
 COMM                MONEY,
 DEPTNO              INTEGER NOT NULL,
 CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
 CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (EMPNO));

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-81',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-81',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-81',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-81',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-81',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-81',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-82',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-83',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);


SELECT * FROM EMP;
SELECT * FROM DEPT;

--DISPLAY ALL THE EMP IN THE ASCEDING ORDER OF NAME

SELECT * FROM EMP ORDER BY ENAME ASC;

--DISPLAY ALL THE EMP NAMES IN LOWER CASE

SELECT LOWER(ENAME) FROM EMP;

--DISPLAY ALL THE ENAMES, SALARY, COMMISISON

SELECT ENAME, SAL, COMM FROM EMP;

--DISPLAY ALL THE EMP WHOSE COMMISION IS NULL
SELECT * FROM EMP WHERE COMM IS NULL;

--DISPLAY ALL THE EMP,SALARY,COMMISION, ANNUALSALARY AS CTC
SELECT ENAME, SAL, COMM, (SAL* 12) + (ISNULL(COMM, 0 ) *12) AS CTC FROM EMP;

-- DISPLAY ALL THE EMP HAVING DEPT IN 10
SELECT * FROM EMP WHERE DEPTNO = 10;

-- DISPLAY ALL THE EMP HAVING DEPT IN 20
SELECT * FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20;

-- DISPLAY ALL THE DETAILS OF EMP SCOTT 
SELECT * FROM EMP WHERE ENAME = 'SCOTT';

-- DISPLAY ALL THE TOP 3 SALARY
SELECT TOP (3) ENAME, SAL, COMM, (SAL* 12) + (ISNULL(COMM, 0 ) *12) AS CTC FROM EMP ORDER BY CTC DESC;

-- DISPLAY EMP WHOSE NAME STARTS WITH A
SELECT ENAME  FROM EMP WHERE ENAME LIKE 'A%';

-- DISPLAY EMP WHOSE NAME CONTAINS  S
SELECT ENAME  FROM EMP WHERE ENAME LIKE '%S%';

-- DISPLAY EMP WHOSE NAME ENDS WITH N
SELECT ENAME  FROM EMP WHERE ENAME LIKE '%N';

-- DISPLAY EMP WHOSE DEPT NO OF SCOTT
SELECT *  FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME ='SCOTT');

-- DISPLAY EMP WHOSE SALARY = SCOTT
SELECT *  FROM EMP WHERE SAL = (SELECT SAL FROM EMP WHERE ENAME ='SCOTT');

-- DISPLAY UNIQUE DEPT NO
SELECT DEPTNO  FROM EMP ;
SELECT DISTINCT(DEPTNO) AS UNIQUE_DEPT FROM EMP ;

-- DISPLAY DATE IN DD-MM-YY FORMAT
SELECT CONVERT(VARCHAR,CONVERT(DATE,HIREDATE,6),3)  FROM EMP ;

-- DISPLAY HEADCOUNT
SELECT COUNT(*) AS HEADCOUNT  FROM EMP ;

-- DISPLAY TOTAL SALARY
SELECT SUM((SAL* 12) + (ISNULL(COMM, 0 ) *12)) AS TOTAL_SAL  FROM EMP ;

-- DISPLAY TOTAL SALARY
SELECT COUNT(*) AS EMP_IN_10  FROM EMP WHERE DEPTNO = 10 ;

-- DISPLAY ENAME , DEPTNAME
SELECT D.DEPTNO,DNAME , ENAME  
	FROM EMP  AS E INNER JOIN DEPT AS D 
	ON E.DEPTNO = D.DEPTNO;

-- DISPLAY ALL DEPARTMENTS AND EMPLOYEES IF ANY
SELECT D.DEPTNO,DNAME , ENAME  
	FROM DEPT  AS D LEFT OUTER JOIN EMP AS E 
    ON E.DEPTNO = D.DEPTNO;

-- DISPLAY ALL DEPARTMENTS AND EMPLOYEES WHERE NO EMPLOYEES ARE THERE
SELECT D.DEPTNO,DNAME , ENAME  
	FROM DEPT  AS D LEFT OUTER JOIN EMP AS E 
	ON E.DEPTNO = D.DEPTNO WHERE ENAME IS NULL;

-- DISPLAY ALL DEPARTMENTS AND EMPLOYEES IF ANY
SELECT D.ENAME AS BOSS, E.ENAME AS EMPLOYEE 
	FROM EMP AS E INNER JOIN EMP AS D 
	ON E.MGR = D.EMPNO; 

-- Display all the number of employees by Dept Wise
SELECT DEPTNO, COUNT(DEPTNO) as NO_OF_EMP FROM EMP GROUP BY DEPTNO;

-- Display all the number of employees by Job Wise
SELECT JOB, COUNT(JOB) as NO_OF_EMP FROM EMP GROUP BY JOB;

-- Display all the number of employees by Deptwise, Jobwise
SELECT DEPTNO , JOB, COUNT(JOB) as NO_OF_EMP FROM EMP GROUP BY JOB,DEPTNO;